###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "olivita",
    "age": "31",
    "email": "rafasv41@gmail.com",
    "origin": "España"
}

###

GET http://localhost:9000/api/users HTTP/1.1

###

GET http://localhost:9000/api/users/630e1f3ff3e9366bcbc4b3de HTTP/1.1


###
PUT  http://localhost:9000/api/users/630e1f3ff3e9366bcbc4b3de HTTP/1.1
Content-Type: application/json

{
    "name": "Rafael Manuel Sánchez Villanueva",
    "age": "31",
    "email": "rafasv41@gmail.com",
    "origin": "España"
}


###

DELETE  http://localhost:9000/api/users/630e3eacd761a0e94939870b HTTP/1.1




