###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "olivita",
    "age": "31",
    "email": "rafasv41@gmail.com",
    "origin": "Holanda"
}

###

GET http://localhost:9000/api/users HTTP/1.1

###

GET http://localhost:9000/api/users/630e1f3ff3e9366bcbc4b3de HTTP/1.1


###
PUT  http://localhost:9000/api/users/630e1f3ff3e9366bcbc4b3de HTTP/1.1
Content-Type: application/json

{
    "name": "Rafael Manuel Sánchez Villanueva",
    "age": "31",
    "email": "rafasv41@gmail.com",
    "origin": "España"
}


###

DELETE  http://localhost:9000/api/users/630e3eacd761a0e94939870b HTTP/1.1


////////////////////////////////////////////////// WINES ////////////////////////////////////////

//Wine Create

###

POST http://localhost:9000/api/wines HTTP/1.1
Content-Type: application/json

{
    "nameOfWine": "Papachanga",
    "typeOfWine": "Fino",
    "winery": "ololololdfgdfg",
    "typeOfGrape": "Palomino",
    "description": "sfsddsfsddfg",
    "alcoholStrength": "16",
    "imgURL": "sdfsdfsddgd"
}

###

GET http://localhost:9000/api/wines HTTP/1.1

###

GET http://localhost:9000/api/wines/6312417abfaf36399c44218a HTTP/1.1




